services:
  - type: web
    name: simplifymoney-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev python3-pip python3-venv
      python3 -m pip install --upgrade pip setuptools wheel
      python3 -m pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: simplifymoney-db
          property: connectionString
      - key: API_URL
        value: https://simplifymoney-backend.onrender.com
      - key: TORCH_HOME
        value: /tmp/torch
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
