services:
  - type: web
    name: simplifymoney-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: simplifymoney-db
          property: connectionString
      - key: API_URL
        value: https://simplifymoney-backend.onrender.com
